spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    maxActivec: 20
    initalSize: 1
    maxWait: 60000
    poolPreparedStatements: true
    maxPoolPreparedStatementsPerConnectionSize: 20
    ##慢sql日志打印
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minldle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
